// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebappAPI.Data;

#nullable disable

namespace WebappAPI.Migrations
{
    [DbContext(typeof(MusicDbContext))]
    [Migration("20260421081120_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("WebappAPI.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "aespa",
                            Duration = "3:15",
                            Title = "Supernova"
                        },
                        new
                        {
                            Id = 2,
                            Artist = "aespa",
                            Duration = "3:24",
                            Title = "Armageddon"
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Son Tung M-TP",
                            Duration = "4:05",
                            Title = "Hay Trao Cho Anh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
